import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'
import { Footer } from '../components'
import Header from '../components/Header'

const geistSans = localFont({
  src: './assets/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './assets/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid min-h-dvh grid-rows-[auto_1fr_auto] antialiased`}
      >
        <Header />
        <main className="container mx-auto px-1 sm:px-2 lg:px-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
